# Generated by Django 5.1.4 on 2026-03-15 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0004_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Subir imagen del producto', upload_to='products/%Y/%m/%d/')),
                ('alt_text', models.CharField(blank=True, default='Imagen del producto', help_text='Texto alternativo para accesibilidad', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición (0 es la primera)')),
                ('is_primary', models.BooleanField(default=False, help_text='Marcar como imagen principal')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'ordering': ['order', 'created'],
                'indexes': [models.Index(fields=['product', 'order'], name='catalog_pro_product_631828_idx'), models.Index(fields=['is_primary'], name='catalog_pro_is_prim_69a078_idx')],
            },
        ),
    ]
