# Generated by Django 5.1.4 on 2026-03-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_reduced',
            field=models.BooleanField(default=False),
        ),
    ]
